services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: new_shop
      POSTGRES_PASSWORD: hard_password1234
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server"]

volumes:
  pgdata:
  redisdata:
