services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: new_shop
      POSTGRES_PASSWORD: hard_password1234
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: