class Strings:
    """
    Class for storing strings in russian.
    """
    welcome = 'Добро пожаловать!'
    ask_subscribe = 'Подписаться на канал'
    check_subscribe = 'Проверить подписку'
    not_subscribed = 'Вы не подписаны на канал'
    main_menu = 'Главное меню'
    lot_list = 'Товар'
    profile = 'Профиль'
    support = 'Поддержка'
    available = 'В наличии: '
    price = 'Цена: '
    pcs = 'шт.'
    lot_buy_desc = 'Сколько хотите приобрести?\nВведите количество в диалог чата.\nМаксимально - 20 шт.'
    category = 'Выбери категорию: '
    input_exception = 'Ошибка при введении количества. Вводите только цифры.'
    input_quantity_exception = 'Ошибка при введении количества. Максимально - 20 шт.'
    input_quantity_available = 'Недостаточно товара в наличии.'
    input_balance_exception = 'Недостаточно баланса для резервирования товара.'
    quantity = 'Количество: '
    total = 'Итого: '
    acc_balance = 'Ваш баланс: '
    purchase = 'Оплатить'