class Strings:
    """
    Class for storing strings in russian.
    """
    welcome = 'Добро пожаловать!'
    ask_subscribe = 'Подписаться на канал'
    check_subscribe = 'Проверить подписку'
    not_subscribed = 'Вы не подписаны на канал'
    main_menu = 'Главное меню'
    lot_list = 'Товар'
    profile = 'Профиль'
    support = 'Поддержка'
    available = 'В наличии: '
    price = 'Цена: '
    pcs = 'шт.'
    lot_buy_desc = 'Сколько хотите приобрести?\nВведите количество в диалог чата.\nМаксимально - 20 шт.'
    category = 'Выбери категорию: '
    input_exception = 'Ошибка при введении количества. Вводите только цифры.'
    input_quantity_exception = 'Ошибка при введении количества. Максимально - 20 шт.'
    input_quantity_available = 'Недостаточно товара в наличии.'
    input_balance_exception = 'Недостаточно баланса для резервирования товара.'
    input_negative_number = 'Ошибка при введении количества. Вводите только положительные числа.'
    quantity = 'Количество: '
    total = 'Итого: '
    acc_balance = 'Ваш баланс: '
    purchase = 'Оплатить'
    add_funds = 'Пополнить баланс'
    ids = 'ID:'
    registration_date = "Дата регистрации"
    purchase_quantity = "Кол-во покупок"
    topup_desc = "Напишите сумму к пополнению кошелька ниже"
    payment_desc = 'Оплатите чек и ждите обработку платежа'
    accept_payment = 'Принять оплату'
    payment_bill = 'Чек на оплату в CryptoBot'
    payment_exception = "Оплата не прошла"
    topup_exception = 'Ошибка при пополнении баланса'
    topup_success = 'Баланс пополнен на . Приятных покупок'
    redis_expire = 'Срок резерва истек.'
    admin_panel = 'Панель администратора'
    admin_panel_desc = 'Привет, '
    admin_add_lots = 'Добавить товары'
    admin_add_lots_desc = 'Укажите имя лота и цену через запятую.\nПример:\nKleinanzeigen (GMX.COM), 10'
    admin_add_lots_exception = 'Не правильный формат ввода данных'
    admin_add_lots_zip = 'Отправь сюда zip архив в котором будут txt файлы с куками'
    zip_archive_exception = 'Неправильный формат архива'
    download_error = 'Не удалось скачать файл'
    no_files = 'В архиве нет файлов'
    duplicate_logs = 'Обнаружен дубликат при покупке. Файл: '
    duplicate_download = 'Обнаружен дубликат при загрузке. Файл: '
    admin_change_balance = 'Пополнить баланс'
    admin_change_price = 'Изменить цену товара'
    
